version: "3.3"

services:

  site:
    image: docsy/docsy-example
    build:
      context: .
    command: server --baseURL "http://172.30.6.135/"
    ports:
      - "1313:1313"
    volumes:
      - .:/src
